spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MONEY_LENDING_DB?createDatabaseIfNotExist=true
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      password: 1111
      name: user
server:
  port: 8081


